# KallistiOS ##version##
#
# arch/dreamcast/math/Makefile
# (c)2001 Megan Potter
#

# Dreamcast-specific math functions

OBJS = fmath.o math.o matrix.o matrix3d.o matrix_stack.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab

