# KallistiOS ##version##
#
# arch/dreamcast/hardware/maple/mie/Makefile
# Copyright (C) 2026 Ruslan Rostovtsev
#

OBJS := mie.o mie_proto.o mie_input.o mie_calib.o mie_fw.o

include $(KOS_BASE)/Makefile.prefab
