# KallistiOS ##version##
#
# addons/libgprof/Makefile
# Copyright (C) 2025 Andy Barajas
#

TARGET = libgprof.a

# Portable core. The per-architecture backend object(s) are appended by the
# matching kos/$(KOS_ARCH).cnf (e.g. arch/dreamcast/trap.o).
OBJS = gmon.o

include $(KOS_BASE)/addons/Makefile.prefab
