# KallistiOS ##version##
#
# arch/dreamcast/fs/Makefile
# (c)2001 Megan Potter
# Copyright (C) 2026 Joseph Black
#

# Dreamcast-specific file systems

OBJS  = fs_iso9660.o fs_vmu.o fs_dcload.o vmufs.o vmufs_validate.o \
        vmufs_chain.o vmufs_maintenance_model.o vmufs_defrag_schedule.o
SUBDIRS =

include $(KOS_BASE)/Makefile.prefab
