/* KallistiOS ##version##

   dc/vmufs_meta.h
   Copyright (C) 2003 Megan Potter
   Copyright (C) 2026 Joseph Black

*/

/** \file    dc/vmufs_meta.h
    \brief   VMU filesystem metadata and validation.
    \ingroup vfs_vmu

    This header contains the on-card structures and validation routines that
    do not require a Maple device. They can be used by KOS applications and by
    host-side image inspection tools.

    \author Megan Potter
    \author Joseph Black
*/

#ifndef __DC_VMUFS_META_H
#define __DC_VMUFS_META_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** \addtogroup vfs_vmu
    @{
*/

#define VMUFS_BLOCK_SIZE       512u    /**< \brief Bytes in a VMU block. */
#define VMUFS_FAT_FREE         0xfffcu /**< \brief Unallocated FAT entry. */
#define VMUFS_FAT_EOF          0xfffau /**< \brief End-of-file FAT marker. */
#define VMUFS_FILETYPE_DATA    0x33u   /**< \brief Data-file directory type. */
#define VMUFS_FILETYPE_GAME    0xccu   /**< \brief Executable directory type. */

/** \brief Standard 128 KiB card geometry generated by KOS. */
#define VMUFS_STANDARD_CARD_BLOCKS 256u
#define VMUFS_STANDARD_USER_BLOCKS 200u
#define VMUFS_STANDARD_ROOT_BLOCK  255u
#define VMUFS_STANDARD_FAT_BLOCK   254u
#define VMUFS_STANDARD_DIR_BLOCK   253u
#define VMUFS_STANDARD_DIR_BLOCKS  13u
/** \brief BCD timestamp used by the VMU filesystem. */
typedef struct {
    uint8_t cent;   /**< \brief Century */
    uint8_t year;   /**< \brief Year, within century */
    uint8_t month;  /**< \brief Month of the year */
    uint8_t day;    /**< \brief Day of the month */
    uint8_t hour;   /**< \brief Hour of the day */
    uint8_t min;    /**< \brief Minutes */
    uint8_t sec;    /**< \brief Seconds */
    uint8_t dow;    /**< \brief Day of week (0 = Monday, etc.) */
} vmu_timestamp_t;

/** \brief VMU filesystem root-block layout. */
typedef struct {
    uint8_t         magic[16];       /**< \brief All should contain 0x55 */
    uint8_t         use_custom;      /**< \brief 0 = standard, 1 = custom */
    uint8_t         custom_color[4]; /**< \brief Blue, green, red, alpha */
    uint8_t         pad1[27];        /**< \brief All zeros */
    vmu_timestamp_t timestamp;       /**< \brief BCD timestamp */
    uint8_t         pad2[8];         /**< \brief All zeros */
    uint8_t         unk1[6];         /**< \brief Reserved format bytes */
    uint16_t        fat_loc;         /**< \brief FAT location */
    uint16_t        fat_size;        /**< \brief FAT size in blocks */
    uint16_t        dir_loc;         /**< \brief Directory location */
    uint16_t        dir_size;        /**< \brief Directory size in blocks */
    uint16_t        icon_shape;      /**< \brief Icon shape for this card */
    uint16_t        blk_cnt;         /**< \brief Number of user blocks */
    uint8_t         unk2[430];       /**< \brief Reserved format bytes */
} vmu_root_t;

/** \brief VMU filesystem directory entry, 32 bytes. */
typedef struct {
    uint8_t         filetype;       /**< \brief Zero, data, or executable */
    uint8_t         copyprotect;    /**< \brief 0x00 copyable, 0xff protected */
    uint16_t        firstblk;       /**< \brief First block in the file */
    char            filename[12];   /**< \brief Not null-terminated */
    vmu_timestamp_t timestamp;      /**< \brief File timestamp */
    uint16_t        filesize;       /**< \brief File size in blocks */
    uint16_t        hdroff;         /**< \brief Header offset in blocks */
    uint8_t         dirty;          /**< \brief In-memory writeback flag */
    uint8_t         pad1[3];        /**< \brief All zeros on card */
} vmu_dir_t;

/** \brief Mutable directory attributes for an existing VMU file. */
typedef struct vmufs_file_attributes {
    uint16_t header_offset; /**< \brief File-header offset in 512-byte blocks. */
    uint8_t copy_protected; /**< \brief Nonzero prevents manager-level copies. */
} vmufs_file_attributes_t;

/** \brief High-level state of the filesystem found on a memory card. */
typedef enum vmufs_volume_state {
    /** No valid root magic, including an interrupted format. */
    VMUFS_VOLUME_UNFORMATTED,
    /** Valid geometry, directory, FAT, and file ownership. */
    VMUFS_VOLUME_READY,
    /** Structurally safe filesystem with allocated orphan blocks. */
    VMUFS_VOLUME_DEGRADED,
    /** Recognized but unsafe root or filesystem metadata. */
    VMUFS_VOLUME_CORRUPT,
    /** Recognized geometry that this VMUFS implementation cannot address. */
    VMUFS_VOLUME_UNSUPPORTED
} vmufs_volume_state_t;

/** \brief Parameters stored in a newly formatted standard VMU root block. */
typedef struct vmufs_format_options {
    uint8_t use_custom_color;  /**< \brief Whether custom_color is active. */
    uint8_t custom_color[4];   /**< \brief Blue, green, red, and alpha. */
    vmu_timestamp_t timestamp; /**< \brief Volume creation timestamp. */
    uint16_t icon_shape;       /**< \brief Volume icon shape, from 0 to 123. */
} vmufs_format_options_t;

/** \brief Amount of existing card data cleared by vmufs_format(). */
typedef enum vmufs_format_mode {
    VMUFS_FORMAT_QUICK, /**< \brief Rewrite filesystem metadata only. */
    VMUFS_FORMAT_FULL   /**< \brief Clear data blocks before metadata. */
} vmufs_format_mode_t;

/** \brief First detected VMU metadata inconsistency. */
typedef enum vmufs_validation_error {
    VMUFS_VALIDATION_OK = 0,
    VMUFS_VALIDATION_INVALID_ARGUMENT,
    VMUFS_VALIDATION_BAD_ROOT_MAGIC,
    VMUFS_VALIDATION_BAD_ROOT_GEOMETRY,
    VMUFS_VALIDATION_UNSUPPORTED_FAT,
    VMUFS_VALIDATION_BAD_FILE_TYPE,
    VMUFS_VALIDATION_EMPTY_FILE,
    VMUFS_VALIDATION_CHAIN_OUT_OF_RANGE,
    VMUFS_VALIDATION_CHAIN_EARLY_END,
    VMUFS_VALIDATION_CHAIN_TOO_LONG,
    VMUFS_VALIDATION_CHAIN_CYCLE,
    VMUFS_VALIDATION_CHAIN_CROSSLINK,
    VMUFS_VALIDATION_DUPLICATE_NAME,
    VMUFS_VALIDATION_ORPHAN_BLOCK
} vmufs_validation_error_t;

/** \brief Summary produced by vmufs_validate(). */
typedef struct vmufs_validation {
    vmufs_validation_error_t first_error; /**< \brief First inconsistency */
    size_t first_dir_index;                /**< \brief Associated entry */
    uint16_t first_block;                  /**< \brief Associated block */
    size_t error_count;                    /**< \brief Total issues found */
    size_t file_count;                     /**< \brief Occupied dir entries */
    size_t free_dir_entries;               /**< \brief Empty dir entries */
    size_t free_blocks;                    /**< \brief Free user blocks */
    size_t used_blocks;                    /**< \brief Allocated user blocks */
    size_t reachable_blocks;               /**< \brief Blocks owned by files */
    size_t orphan_blocks;                  /**< \brief Allocated but unowned */
    size_t executable_free_blocks;         /**< \brief Free prefix at block 0 */
} vmufs_validation_t;

/** \brief Filesystem geometry, volume settings, and allocation summary. */
typedef struct vmufs_volume_info {
    vmufs_volume_state_t state;       /**< \brief Classified volume state. */
    vmufs_format_options_t format;    /**< \brief Stored volume settings. */
    size_t total_blocks;              /**< \brief Addressable user blocks. */
    size_t directory_entries;         /**< \brief Total directory capacity. */
    vmufs_validation_t validation;    /**< \brief Ownership and free-space data. */
} vmufs_volume_info_t;

/** \brief Detailed outcome of a multi-file deletion. */
typedef struct vmufs_delete_result {
    size_t requested_files; /**< \brief Number of requested names. */
    size_t deleted_files;   /**< \brief Positively acknowledged removals. */
    size_t reclaimed_blocks; /**< \brief Positively acknowledged FAT cleanup. */
    uint8_t directory_complete; /**< \brief Every requested entry was removed. */
    uint8_t directory_state_uncertain; /**< \brief A directory write was unacknowledged. */
    uint8_t allocation_cleanup_complete; /**< \brief Confirmed removals have no leaked blocks. */
} vmufs_delete_result_t;

/** \brief Validate root geometry for a card using KOS's root-block location.

    The current KOS VMU block driver supports one 512-byte FAT block. This
    routine rejects geometries that the driver cannot address safely,
    including metadata or user-data ranges that claim physical block 255.

    \param root         Root block to validate.
    \param card_blocks  Total number of blocks in the card image.
    \retval 0           Geometry is supported and internally consistent.
    \retval -1          Geometry is malformed or unsupported; errno is set.
*/
int vmufs_root_validate(const vmu_root_t *root, size_t card_blocks);

/** \brief Validate loaded VMU filesystem metadata.

    Every active directory chain is checked for bounds, exact length, cycles,
    cross-links, duplicate names, and premature termination. Allocated blocks
    not reachable from a directory entry are reported as orphans.

    \param root         Valid root block.
    \param card_blocks  Total number of blocks in the card image.
    \param fat          Loaded FAT entries.
    \param fat_entries  Number of entries available at \p fat.
    \param dir          Loaded directory entries.
    \param dir_entries  Number of entries available at \p dir.
    \param result       Validation summary; initialized on every call.
    \retval 0           Metadata is consistent.
    \retval -1          An inconsistency or invalid argument was found.
*/
int vmufs_validate(const vmu_root_t *root, size_t card_blocks,
                   const uint16_t *fat, size_t fat_entries,
                   const vmu_dir_t *dir, size_t dir_entries,
                   vmufs_validation_t *result);

/** \brief Count the executable-eligible free prefix beginning at block zero. */
size_t vmufs_fat_free_executable(const vmu_root_t *root,
                                 const uint16_t *fat,
                                 size_t fat_entries);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* __DC_VMUFS_META_H */
