# KallistiOS ##version##
#
# loadable/Makefile.prefab
# Copyright (C) 2000, 2003 Megan Potter
# Copyright (C) 2024 Ruslan Rostovtsev
#

include $(KOS_BASE)/Makefile.rules

ifdef DBG_LIBS
DBG_LIBS += -lkallisti_exports
else
DBG_LIBS = -lkallisti_exports
endif

ifdef TARGET_LIB
all: rm-elf $(TARGET) $(TARGET_LIB)
else
all: rm-elf $(TARGET)
endif

# First one checks for missing symbols (and fully links with an offset
# of zero so we can do tracebacks later), second one makes the real file.
$(TARGET): $(OBJS)
	$(KOS_CC) $(KOS_CFLAGS) -fno-lto -Wl,-Ttext=0x00000000 -e 0x00000000 -nostartfiles -nodefaultlibs -o dbg-$(TARGET) $(OBJS) $(KOS_LIB_PATHS) -Wl,--start-group $(LIBS) $(DBG_LIBS) -lgcc -Wl,--end-group
	$(KOS_CC) $(KOS_CFLAGS) -fno-lto -Wl,-d -Wl,-r -Wl,-S -Wl,-x -nostartfiles -nodefaultlibs -o $(TARGET) -Wl,-T $(KOS_BASE)/loadable/shlelf_dc.xr $(OBJS) $(KOS_LIB_PATHS) -Wl,--start-group $(LIBS) -lgcc -Wl,--end-group
	$(KOS_SIZE) $(TARGET)

clean:
	-rm -f $(OBJS) $(TARGET) dbg-$(TARGET) $(TARGET_LIB) romdisk.* exports.c exports_stubs.*

rm-elf:
	-rm -f $(TARGET) dbg-$(TARGET) $(TARGET_LIB)
